# Generated by Django 6.0.2 on 2026-02-19 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_alter_recipeingredient_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeingredient',
            options={'ordering': ['quantity'], 'verbose_name': 'recipe ingredient', 'verbose_name_plural': 'recipe ingredients'},
        ),
    ]
