# Generated by Django 6.0.2 on 2026-03-02 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0007_alter_recipe_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(max_length=255),
        ),
    ]
